apiVersion: apps/v1
kind: Deployment
metadata:
  name: khem-deployment
  namespace: default
  labels:
    app: khem
spec:
  replicas: 2
  selector:
    matchLabels:
      app: khem
  template:
    metadata:
      labels:
        app: khem
    spec:
      containers:
      - name: khem
        image: khem:latest
        ports:
        - containerPort: 80
